language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd test-app
  - yarn install
  - yarn test
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  local_dir: build
  on:
branch: master
